In [7]:
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib as plt

ModuleNotFoundError: No module named 'geopandas'

### Data Collection

In [14]:
violation19 = pd.read_csv("data/Housing_Maintenance_Code_Violations_2019.csv")
violation21 = pd.read_csv("data/Housing_Maintenance_Code_Violations_2021.csv")
violation24 = pd.read_csv("data/Housing_Maintenance_Code_Violations_2024.csv")

In [16]:
violation19.head()

,ViolationID,BuildingID,BoroID,Borough,Block,Lot,Class,ApprovedDate,OriginalCorrectByDate,NewCorrectByDate,CurrentStatusID,CurrentStatus,ViolationStatus,RentImpairing,NOVDescription
0,12833362,49163,2,BRONX,3103,26,A,01/02/2019,04/08/2019,NaN,9,VIOLATION DISMISSED,Close,N,§ 27-2005 ADM CODE REPAIR THE BROKEN OR DEFECT...
1,12832253,115647,2,BRONX,2846,74,A,01/02/2019,04/08/2019,NaN,19,VIOLATION CLOSED,Close,N,§ 27-2005 ADM CODE PAINT METAL IN ACCORDANCE W...
2,12833436,304527,3,BROOKLYN,1615,73,B,01/02/2019,02/07/2019,NaN,22,FIRST NO ACCESS TO RE- INSPECT VIOLATION,Open,N,§ 27-2018 ADMIN. CODE: ABATE THE NUISANCE CONS...
3,12832401,94487,2,BRONX,2952,53,B,01/02/2019,02/07/2019,NaN,19,VIOLATION CLOSED,Close,N,§ 27-2005 ADM CODE REPAIR THE BROKEN OR DEFECT...
4,12831837,119895,2,BRONX,3057,11,B,01/02/2019,02/07/2019,NaN,21,NOT COMPLIED WITH,Open,N,§ 27-2005 ADM CODE PROPERLY REPAIR THE BROKEN ...

In [18]:
violation21.head()

,ViolationID,BuildingID,BoroID,Borough,Block,Lot,Class,ApprovedDate,OriginalCorrectByDate,NewCorrectByDate,CurrentStatusID,CurrentStatus,ViolationStatus,RentImpairing,NOVDescription
0,13967451,294910,3,BROOKLYN,5230,76,B,01/02/2021,02/08/2021,NaN,22,FIRST NO ACCESS TO RE- INSPECT VIOLATION,Open,N,§ 27-2017.3 HMC: TRACE AND REPAIR THE SOURCE A...
1,13894931,10065,1,MANHATTAN,2241,2,C,01/02/2021,01/10/2021,NaN,19,VIOLATION CLOSED,Close,N,§ 27-2005 ADM CODE & 309 M/D LAW ABATE THE NUI...
2,13894980,4175,1,MANHATTAN,2046,7,C,01/02/2021,01/30/2021,NaN,19,VIOLATION CLOSED,Close,N,"§ 27-2005, 27-2007, 27-2041.1 HMC: REPLACE OR ..."
3,13965393,68459,2,BRONX,4700,28,C,01/02/2021,01/30/2021,NaN,47,NOTICE OF ISSUANCE SENT TO TENANT,Open,N,HMC ADM CODE: § 27-2017.4 ABATE THE INFESTATIO...
4,13965388,348145,3,BROOKLYN,5329,62,A,01/02/2021,04/09/2021,NaN,19,VIOLATION CLOSED,Close,N,§ 27-2013 ADM CODE PAINT WITH LIGHT COLORED PA...

In [20]:
violation24.head()

,ViolationID,BuildingID,BoroID,Borough,Block,Lot,Class,ApprovedDate,OriginalCorrectByDate,NewCorrectByDate,CurrentStatusID,CurrentStatus,ViolationStatus,RentImpairing,NOVDescription
0,16566210,39531,1,MANHATTAN,1966,42,B,01/02/2024,02/07/2024,NaN,19,VIOLATION CLOSED,Close,Y,§ 27-2005 ADM CODE REPAIR THE ROOF SO THAT IT ...
1,16555062,64683,2,BRONX,2432,47,B,01/02/2024,02/07/2024,NaN,19,VIOLATION CLOSED,Close,N,§ 27-2005 HMC: PROPERLY REPAIR OR REPLACE THE ...
2,16566751,81924,2,BRONX,3310,40,A,01/02/2024,04/07/2024,NaN,9,VIOLATION DISMISSED,Close,N,§ 27-2013 ADM CODE PAINT WITH LIGHT COLORED PA...
3,16558287,228366,3,BROOKLYN,1296,14,A,01/02/2024,04/07/2024,NaN,9,VIOLATION DISMISSED,Close,N,§ 27-2005 ADM CODE REPAIR THE BROKEN OR DEFECT...
4,16560902,295908,3,BROOKLYN,1217,9,C,01/02/2024,01/03/2024,NaN,19,VIOLATION CLOSED,Close,N,"§ 27-2028, 2032 ADM CODE PROVIDE AN ADEQUATE S..."

# Univariate Map

In [22]:
violation19

,ViolationID,BuildingID,BoroID,Borough,Block,Lot,Class,ApprovedDate,OriginalCorrectByDate,NewCorrectByDate,CurrentStatusID,CurrentStatus,ViolationStatus,RentImpairing,NOVDescription
0,12833362,49163,2,BRONX,3103,26,A,01/02/2019,04/08/2019,NaN,9,VIOLATION DISMISSED,Close,N,§ 27-2005 ADM CODE REPAIR THE BROKEN OR DEFECT...
1,12832253,115647,2,BRONX,2846,74,A,01/02/2019,04/08/2019,NaN,19,VIOLATION CLOSED,Close,N,§ 27-2005 ADM CODE PAINT METAL IN ACCORDANCE W...
2,12833436,304527,3,BROOKLYN,1615,73,B,01/02/2019,02/07/2019,NaN,22,FIRST NO ACCESS TO RE- INSPECT VIOLATION,Open,N,§ 27-2018 ADMIN. CODE: ABATE THE NUISANCE CONS...
3,12832401,94487,2,BRONX,2952,53,B,01/02/2019,02/07/2019,NaN,19,VIOLATION CLOSED,Close,N,§ 27-2005 ADM CODE REPAIR THE BROKEN OR DEFECT...
4,12831837,119895,2,BRONX,3057,11,B,01/02/2019,02/07/2019,NaN,21,NOT COMPLIED WITH,Open,N,§ 27-2005 ADM CODE PROPERLY REPAIR THE BROKEN ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668532,13523433,230724,3,BROOKLYN,1207,72,C,12/31/2019,01/23/2020,NaN,19,VIOLATION CLOSED,Close,N,"§ 27-2005, 27-2007, 27-2041.1 HMC: REPLACE OR ..."
668533,13523436,230724,3,BROOKLYN,1207,72,A,12/31/2019,04/06/2020,NaN,21,NOT COMPLIED WITH,Open,N,§ 26-1103 ADMIN. CODE: POST AND MAINTAIN A PRO...
668534,13523441,230724,3,BROOKLYN,1207,72,C,12/31/2019,01/10/2020,NaN,2,NOV SENT OUT,Open,N,§ 27-2033 ADM CODE PROVIDE READY ACCESS TO BUI...
668535,13520475,388756,3,BROOKLYN,1979,7,B,12/31/2019,06/25/2025,NaN,11,VIOLATION WILL BE REINSPECTED,Open,N,§ 27-2005 ADM CODE PROPERLY REPAIR THE BROKEN ...
668536,13524779,769123,5,STATEN ISLAND,2922,265,C,12/31/2019,01/10/2020,NaN,11,VIOLATION WILL BE REINSPECTED,Open,N,§ 27-2005 ADM CODE & 309 M/D LAW ABATE THE NUI...

# Bar Graph